name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Application Configuration
      PORT: ${{ secrets.PORT }}
      APP_ENV: test
      SIGNATURE_EXPIRY: 30
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }} 
      MAIL_USER: ${{ secrets.MAIL_USER }} 
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }} 
      MAIL_SENDER: ${{ secrets.MAIL_SENDER }} 
             

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Build Docker Image
        run: docker build -t constructthecompany/api_construction:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push constructthecompany/api_construction:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      # Application Configuration
      PORT: ${{ secrets.PORT }}
      APP_ENV: test
      SIGNATURE_EXPIRY: 30
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }} 
      MAIL_USER: ${{ secrets.MAIL_USER }} 
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }} 
      MAIL_SENDER: ${{ secrets.MAIL_SENDER }} 

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # Pull the latest Docker image
            docker pull constructthecompany/api_construction:latest

            # Stop and remove the existing container if running
            docker stop api_construction || true
            docker rm api_construction || true

            # Run the new Docker container with the environment variables
            docker run -d \
              --name api_construction \
              -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              -e PORT=${{ secrets.PORT }} \
              -e APP_ENV=${{ secrets.APP_ENV }} \
              -e SIGNATURE_EXPIRY=${{ secrets.SIGNATURE_EXPIRY }} \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
              -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \

              -e MAIL_HOST=${{ secrets.MAIL_HOST }} \
              -e MAIL_PORT=${{ secrets.MAIL_PORT }} \
              -e MAIL_USER=${{ secrets.MAIL_USER }} \
              -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              -e MAIL_SENDER=${{ secrets.MAIL_SENDER }} \
              constructthecompany/api_construction:latest
